---
- name: Create isucon group
  become: yes
  become_user: root
  group:
    name: isucon
    gid: 1002
    state: present
    system: no

- name: Create isucon user
  become: yes
  become_user: root
  user:
    name: isucon
    uid: 1002
    group: isucon
    password: isucon
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  become: yes
  become_user: root
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-user
    owner: root
    group: root
    mode: 0440

- name: Install Development Tools
  become: yes
  become_user: root
  apt: name="{{ item }}" state=present
  with_items:
    - "build-essential"

- name: Install packages
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - curl
    - dstat
    - libgdbm-dev
    - git
    - jq
    - libffi-dev
    - libyaml-dev
    - ncurses-dev
    - libssl1.0-dev
    - patch
    - libreadline-dev
    - sudo
    - zlib1g-dev

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /home/isucon/xbuild
    version: master

- name: mkdir /home/isucon/local for xbuild
  become: yes
  become_user: isucon
  file: path=/home/isucon/local
    state=directory
