---
# - name: firewalld open tcp 80 port
#   become: yes
#   become_user: root
#   firewalld:
#     immediate: true
#     permanent: true
#     service: http
#     state: enabled

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Put default-h2o.conf
  become: yes
  become_user: root
  copy:
    src: default-h2o.conf
    dest: /etc/h2o/default-h2o.conf

- name: Put php-h2o.conf
  become: yes
  become_user: root
  copy:
    src: php-h2o.conf
    dest: /etc/h2o/php-h2o.conf

- name: Remove h2o.conf
  become: yes
  become_user: root
  file:
    state: absent
    path: /etc/h2o/h2o.conf

- name: Put h2o.conf link
  become: yes
  become_user: root
  file:
    state: link
    src: /etc/h2o/default-h2o.conf
    dest: /etc/h2o/h2o.conf

- name: Put h2o.service
  become: yes
  become_user: root
  copy:
    src: h2o.service
    dest: /lib/systemd/system/h2o.service

- name: Put torb.nodejs.service
  become: yes
  become_user: root
  copy:
    src: torb.nodejs.service
    dest: /etc/systemd/system/torb.nodejs.service

- name: Put torb.go.service
  become: yes
  become_user: root
  copy:
    src: torb.go.service
    dest: /etc/systemd/system/torb.go.service

- name: Put torb.perl.service
  become: yes
  become_user: root
  copy:
    src: torb.perl.service
    dest: /etc/systemd/system/torb.perl.service

- name: Put torb.php.service
  become: yes
  become_user: root
  copy:
    src: torb.php.service
    dest: /etc/systemd/system/torb.php.service

- name: Put torb.python.service
  become: yes
  become_user: root
  copy:
    src: torb.python.service
    dest: /etc/systemd/system/torb.python.service

- name: Put torb.ruby.service
  become: yes
  become_user: root
  copy:
    src: torb.ruby.service
    dest: /etc/systemd/system/torb.ruby.service

- name: Install for torb.nodejs
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/webapp/nodejs
  shell: |
    bash -lc "/home/isucon/local/node/bin/npm install"
