---
- name: Append h2o repository
  become: yes
  become_user: root
  blockinfile:
    create: yes
    dest: /etc/yum.repos.d/bintray-tatsushid-h2o-rpm.repo
    content: |
      [bintray-tatsushid-h2o-rpm]
      name=bintray-tatsushid-h2o-rpm
      baseurl=https://dl.bintray.com/tatsushid/h2o-rpm/centos/$releasever/$basearch/
      gpgcheck=0
      repo_gpgcheck=0
      enabled=1

- name: Install h2o
  become: yes
  become_user: root
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - cmake
    - libssl1.0-dev
    - libuv1-dev
    - h2o

- name: Make pid file directory
  become: yes
  become_user: root
  file:
    path: /var/run/h2o
    state: directory
    owner: isucon
    group: isucon
